In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

/home/mqasim/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

# Train Data

In [3]:
train = pd.DataFrame({
    "Att1":[0.8,1.4,2.1,2.6,6.8,8.8,9.2,10.8,11.8,12.4,12.8,14.0,14.2,15.6,15.8,16.6,17.4],
    "Att2":[6.3,8.1,7.4,14.3,12.6,9.8,11.6,9.6,9.9,6.5,1.1,19.9,18.5,17.4,12.2,6.7,4.5],
    "Class":[0,0,0,1,0,1,0,1,1,1,0,1,0,1,0,1,1]
})
train

    Att1  Att2  Class
0    0.8   6.3      0
1    1.4   8.1      0
2    2.1   7.4      0
3    2.6  14.3      1
4    6.8  12.6      0
5    8.8   9.8      1
6    9.2  11.6      0
7   10.8   9.6      1
8   11.8   9.9      1
9   12.4   6.5      1
10  12.8   1.1      0
11  14.0  19.9      1
12  14.2  18.5      0
13  15.6  17.4      1
14  15.8  12.2      0
15  16.6   6.7      1
16  17.4   4.5      1

In [5]:
test = pd.DataFrame({
    "Att1":[0.8,1.4,2.1],
    "Att2":[6.3,8.1,7.4],
    "k1": None,
    "k3": None,
    "k5": None,
    "k6": None
    
})
test

   Att1  Att2    k1    k3    k5    k6
0   0.8   6.3  None  None  None  None
1   1.4   8.1  None  None  None  None
2   2.1   7.4  None  None  None  None

In [ ]:
def root_square_error(y, y_predict):
    return np.sqrt(((y, y_predict)**2).sum())